<?php

namespace RedJasmine\Product\Services\Product\Actions;

use Illuminate\Database\Eloquent\Model;
use RedJasmine\Product\Models\Product;
use RedJasmine\Product\Services\Product\Data\ProductData;
use RedJasmine\Product\Services\Product\Events\ProductUpdatedEvent;
use RedJasmine\Product\Services\Product\ProductService;
use RedJasmine\Product\Services\Product\Validators\ActionAwareValidatorCombiner;
use RedJasmine\Product\Services\Product\Validators\ValidatorAwareValidatorCombiner;
use RedJasmine\Product\Services\Product\Validators\ValidatorCombinerInterface;
use RedJasmine\Support\Data\Data;

/**
 * @property ProductService $service
 * @property Product        $model
 * @property ProductData    $data
 */
class ProductUpdateAction extends AbstractProductStoreAction
{


    public function execute(int|string $key, Data|array $data) : Model
    {
        $this->key = $key;

        $this->data = $data;

        return $this->update();
    }


    protected function after($handleResult) : mixed
    {
        ProductUpdatedEvent::dispatch($handleResult);
        return parent::after($handleResult); // TODO: Change the autogenerated stub
    }


}
