<?php

namespace RedJasmine\Product\Services\Product\Actions;

use Illuminate\Database\Eloquent\Model;
use RedJasmine\Product\Models\Product;
use RedJasmine\Product\Models\ProductInfo;
use RedJasmine\Product\Services\Product\ProductService;
use RedJasmine\Support\Foundation\Service\Actions\ResourceCreateAction;

/**
 * @property ProductService $service
 * @property Product        $model
 */
class ProductCreateAction extends ResourceCreateAction
{
    protected function resolveModel() : void
    {
        if ($this->key) {
            $query       = $this->service::getModel()::query();
            $this->model = $this->service->callQueryCallbacks($query)->findOrFail($this->key);
        } else {
            $product = app($this->getModel());
            $product->setRelation('info', new ProductInfo());
            $product->setRelation('skus', collect([]));
            $this->model = $product;
        }
    }


    public function handle() : Model
    {
        return parent::handle(); // TODO: Change the autogenerated stub
    }


}
