<?php

namespace RedJasmine\Product\Application\Property\Services\Pipelines;


use Closure;
use RedJasmine\Product\Application\Property\Services\ProductPropertyValueQueryService;
use RedJasmine\Product\Application\Property\UserCases\Queries\PropertyValuePaginateQuery;
use RedJasmine\Product\Exceptions\ProductPropertyException;
use RedJasmine\Support\Application\CommandHandler;
use RedJasmine\Support\Application\CommandHandlerPipeline;

class PropertyValueUpdatePipeline extends CommandHandlerPipeline
{
    public function __construct(
        protected ProductPropertyValueQueryService $queryService,
    )
    {
    }


    /**
     * @param CommandHandler $handler
     * @param Closure        $next
     *
     * @return mixed
     * @throws ProductPropertyException
     */
    public function executing(CommandHandler $handler, Closure $next) : mixed
    {

        $hasRepeatCount = $this->queryService
            ->getModelQuery()->where('id', '<>', $handler->aggregate->id)
            ->where('name', $handler->getArguments()[0]->name)
            ->where('pid', $handler->aggregate->pid)->count();

        if ($hasRepeatCount > 0) {
            throw new ProductPropertyException('Property Value Update Failed:', $handler->getArguments()[0]->name);
        }


        return parent::executing($handler, $next); // TODO: Change the autogenerated stub
    }

    public function execute(CommandHandler $handler, Closure $next)
    {

        return parent::execute($handler, $next); // TODO: Change the autogenerated stub
    }

    public function executed(CommandHandler $handler, Closure $next)
    {

        return parent::executed($handler, $next); // TODO: Change the autogenerated stub
    }


}
