<?php

namespace RedJasmine\Product\Application\Property\Services;

use Illuminate\Database\Eloquent\Model;
use RedJasmine\Product\Application\Property\UserCases\Commands\ProductPropertyValueCreateCommand;
use RedJasmine\Product\Application\Property\UserCases\Commands\ProductPropertyValueUpdateCommand;
use RedJasmine\Product\Domain\Property\Models\ProductPropertyValue;
use RedJasmine\Product\Domain\Property\Repositories\ProductPropertyValueRepositoryInterface;
use RedJasmine\Support\Application\ApplicationCommandService;
use RedJasmine\Support\Data\Data;

/**
 * @method ProductPropertyValue create(ProductPropertyValueCreateCommand $command)
 * @method void update(ProductPropertyValueUpdateCommand $command)
 */
class ProductPropertyValueCommandService extends ApplicationCommandService
{
    protected static string $modelClass = ProductPropertyValue::class;

    public function __construct(
        protected ProductPropertyValueRepositoryInterface $repository
    )
    {
        parent::__construct();
    }

    public function newModel($data = null) : Model
    {
        if ($model = $this->repository->findByNameInProperty($data->pid, $data->name)) {
            return $model;
        }
        return parent::newModel($data); // TODO: Change the autogenerated stub
    }


    public function delete(Data $data) : void
    {
        throw new \RuntimeException('does not support');
    }


}
