<?php

namespace RedJasmine\Product\Business\Seller;


use Illuminate\Database\Eloquent\Builder;

class ProductService extends \RedJasmine\Product\Services\Product\ProductService
{
    public function query() : Builder
    {
        $query = parent::query(); // TODO: Change the autogenerated stub

        $query->owner($this->getOwner());

        return $query;
    }


}
